
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";



//export const metadata: Metadata = {
  //title: "Shop Mart",
 // description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
  <Navbar/>
        <div className="container mx-auto p-3">
          <Toaster/>
        {children}
      </div>
     
      </body>
    </html>
  );
}
